export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';

export const NEWS_LIKE = 'NEWS_LIKE';

export const DELETE_CARD = 'DELETE_CARD';

export const SELECTED_NEWS = 'SELECTED_NEWS';
